_BASE_: "mask_rcnn_fbnetv3a_C4.yaml"
QUANTIZATION:
  BACKEND: "qnnpack"
  QAT:
    ENABLED: True
    START_ITER: 0
    ENABLE_OBSERVER_ITER: 0
    DISABLE_OBSERVER_ITER: 500
    FREEZE_BN_ITER: 500
MODEL:
  FBNET_V2:
    NORM: "bn"
  ROI_BOX_HEAD:
    NORM: "bn"
  ROI_MASK_HEAD:
    NORM: "bn"
